version: "3.7"

services:
  orchestrator:
    image: orchestrator
    ports:
      - "8080:8080"

  duckling:
    image: rasa/duckling
    ports:
      - "8000:8000"

  rasa:
    image: rasa-module
    ports:
      - "8081:8081"
      - "5005:5005"
      - "5055:5055"

  ai4bharat:
    image: ai4bharat
    ports:
      - "5001:5001"
    deploy:
      resources:
        limits:
          cpus: "6"
          memory: 10G

  vakyansh:
    image: gcr.io/ekstepspeechrecognition/speech_recognition_model_api:3.0.4
    volumes:
      - /Users/priya/Conversational-Commerce/vakyansh/container_vol:/opt/speech_recognition_open_api/deployed_models/
    ports:
      - "50051:50051"

  keycloak:
    image: keycloak
    ports:
      - "8082:8082"
