version: "3.7"

services:
  react-app:
    container_name: reactapp
    build:
      context: ./packages/client
      dockerfile: Dockerfile
      args:
        CUSTOM_ENV: production
        SERVER_URL: http://localhost:7001
    ports:
      - 1331:80
    networks:
      - react
networks:
  react:
    driver: bridge
